// angular/Citely/src/app/authors/authors.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-authors',
  templateUrl: './authors.component.html',
  styleUrls: ['./authors.component.css']
})
export class AuthorsComponent implements OnInit {
  authors: { id: string, name: string, bio: string, image: string, quoteCount: number }[] = [];
  isLoading = true;
  errorMessage: string | null = null;
  selectedSort: string = 'name';

   // Declare a mapping for authors and their images
   authorImages: { [key: string]: string } = {
    '14th Dalai Lama': 'assets/authors/0.jpg',
    'A. A. Milne': 'assets/authors/AA.jpg',
    'A. P. J. Abdul Kalam': 'assets/authors/K.jpg',
    'A. Powell Davies': 'assets/authors/P.jpg',
    'Abigail Adams': 'assets/authors/Abigail.jpg',
    'Abraham Lincoln': 'assets/authors/L.jpg',
    'Abraham Maslow': 'assets/authors/Abraham.jpg',
    'Adam Smith': 'assets/authors/Smith.jpg',
    'Aeschylus': 'assets/authors/Aeschylus.jpg',
    'Aesop': 'assets/authors/A.jpg',
    'Afrika Bambaataa': 'assets/authors/Afrika.jpg',
    'Agatha Christie': 'assets/authors/Agatha.jpg',
    'Akhenaten': 'assets/authors/Akhenaten.jpg',
    'Alan Cohen': 'assets/authors/Leonard.jpg',
    'Alan Watts': 'assets/authors/Watts.jpg',
    'Albert Camus': 'assets/authors/C.jpg',
    'Albert Einstein': 'assets/authors/ETH.jpg',
    'Albert Schweitzer': 'assets/authors/Schweitzer.jpg',
    'Aldous Huxley': 'assets/authors/Huxley.jpg',
    'Alexander Chalmers': 'assets/authors/Alexander.jpg',
    // Add more mappings as needed
  };
  constructor(private http: HttpClient, private router: Router) {}

  ngOnInit(): void {
    this.getAuthors();
  }

  viewAuthorDetails(authorId: string): void {
    this.router.navigate(['/author', authorId]);
  }

  getAuthors(): void {
    this.isLoading = true;
    this.errorMessage = null;

    this.http.get<{ results: { _id: string, name: string, bio: string, quoteCount: number }[] }>('https://api.quotable.io/authors')
      .subscribe({
        next: (data) => {
          this.isLoading = false;
          if (data && data.results) {
            this.authors = data.results.map((author) => ({
              id: author._id, // Use the correct author ID
              name: author.name,
              bio: author.bio,
              image: this.authorImages[author.name] || 'assets/images/default_author.jpg',
              quoteCount: author.quoteCount,
            }));
            this.sortAuthors(); // Sort by default option
          } else {
            this.errorMessage = 'Les données retournées ne sont pas dans le format attendu.';
          }
        },
        error: (error) => {
          this.isLoading = false;
          console.error('Erreur lors de la récupération des auteurs :', error);
          this.errorMessage = 'Impossible de charger les auteurs. Veuillez réessayer plus tard.';
        },
      });
  }


  sortAuthors(): void {
    if (this.selectedSort === 'name') {
      this.authors.sort((a, b) => a.name.localeCompare(b.name));
    } else if (this.selectedSort === 'quoteCount') {
      this.authors.sort((a, b) => b.quoteCount - a.quoteCount);
    }
  }

  onSortChange(sortValue: string): void {
    this.selectedSort = sortValue;
    this.sortAuthors();
  }
}

<section class="authors-header">
  <video class="bg-video" autoplay muted loop>
    <source src="assets/2.mp4" type="video/mp4">
    Your browser does not support the video tag.
  </video>
  <h1 class="authors-title">Authors</h1>
</section>

<!-- Sorting Dropdown -->
<!-- Sorting Radio Buttons -->
<div class="sort-container">
  <span class="sort-label">Sort By:</span>
  <div class="radio-group">
    <label>
      <input
        type="radio"
        name="sort-authors"
        value="name"
        [(ngModel)]="selectedSort"
        (change)="sortAuthors()" />
      <span class="radio-label">Name</span>
    </label>
    <label>
      <input
        type="radio"
        name="sort-authors"
        value="quoteCount"
        [(ngModel)]="selectedSort"
        (change)="sortAuthors()" />
      <span class="radio-label">Quote Count</span>
    </label>
  </div>
</div>


<div class="authors-section">
  <div
    *ngFor="let author of authors"
    class="author-card"
    [ngStyle]="{'background-image': 'url(' + author.image + ')'}"
    (click)="viewAuthorDetails(author.id)"> <!-- Add click event -->
    <div class="author-info">
      <div class="author-name">{{ author.name }}</div>
      <div class="divider"></div> <!-- Light line divider -->
      <div class="quote-count">Quotes: {{ author.quoteCount }}</div>
      <div class="author-bio">{{ author.bio }}</div> <!-- More info like bio -->
    </div>
  </div>
</div>

// citely-frontend/src/components/Authors.tsx
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import styles from './Author.module.css';

// Define the type for an author
type Author = {
  id: string;
  name: string;
  bio: string;
  image: string;
  quoteCount: number;
};

// Define the type for the error message
type ErrorMessage = string | null;

const Authors = () => {
  const [authors, setAuthors] = useState<Author[]>([]); // Explicitly typing authors as an array of Author objects
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [errorMessage, setErrorMessage] = useState<ErrorMessage>(null); // Updated to handle string | null
  const [selectedSort, setSelectedSort] = useState<'name' | 'quoteCount'>('name');
  const router = useRouter();

  // Declare a mapping for authors and their images
  const authorImages: Record<string, string> = {
    '14th Dalai Lama': '/authors/0.jpg',
    'A. A. Milne': '/authors/AA.jpg',
    'A. P. J. Abdul Kalam': '/authors/K.jpg',
    'A. Powell Davies': '/authors/P.jpg',
    'Abigail Adams': '/authors/Abigail.jpg',
    'Abraham Lincoln': '/authors/L.jpg',
    'Abraham Maslow': '/authors/Abraham.jpg',
    'Adam Smith': '/authors/Smith.jpg',
    'Aeschylus': '/authors/Aeschylus.jpg',
    'Aesop': '/authors/A.jpg',
    'Afrika Bambaataa': '/authors/Afrika.jpg',
    'Agatha Christie': '/authors/Agatha.jpg',
    'Akhenaten': '/authors/Akhenaten.jpg',
    'Alan Cohen': '/authors/Leonard.jpg',
    'Alan Watts': '/authors/Watts.jpg',
    'Albert Camus': '/authors/C.jpg',
    'Albert Einstein': '/authors/ETH.jpg',
    'Albert Schweitzer': '/authors/Schweitzer.jpg',
    'Aldous Huxley': '/authors/Huxley.jpg',
    'Alexander Chalmers': '/authors/Alexander.jpg',
    // Add more mappings as needed
  };

  type AuthorApiResponse = {
    _id: string;
    name: string;
    bio: string;
    quoteCount: number;
  };

  // Fetch authors data from API
  useEffect(() => {
    const fetchAuthors = async () => {
      setIsLoading(true);
      setErrorMessage(null);

      try {
        const response = await fetch('https://api.quotable.io/authors');
        const data = await response.json();

        if (data && data.results) {
          // Map the API response to your Author type
          setAuthors(
            data.results.map((author: AuthorApiResponse) => ({
              id: author._id,
              name: author.name,
              bio: author.bio,
              image: authorImages[author.name] || '/images/default_author.jpg',
              quoteCount: author.quoteCount,
            }))
          );
          sortAuthors(); // Sort by default option
        } else {
          setErrorMessage('Les données retournées ne sont pas dans le format attendu.');
        }
      } finally {
        setIsLoading(false);
      }
    };

    fetchAuthors();
  }, []); // Empty dependency array ensures it runs once when the component mounts

  // Sort authors based on the selected criteria
  const sortAuthors = () => {
    if (selectedSort === 'name') {
      setAuthors((prevAuthors) =>
        [...prevAuthors].sort((a, b) => a.name.localeCompare(b.name))
      );
    } else if (selectedSort === 'quoteCount') {
      setAuthors((prevAuthors) =>
        [...prevAuthors].sort((a, b) => b.quoteCount - a.quoteCount)
      );
    }
  };

  const handleSortChange = (sortValue: 'name' | 'quoteCount') => {
    setSelectedSort(sortValue);
    sortAuthors();
  };

  const handleAuthorClick = (authorId: string) => {
    router.push(`/author/${authorId}`); // Navigate to the author's detail page
  };

  return (
    <div className={styles.container}>
      <section className={styles.header}>
        <video className={styles.bgVideo} autoPlay muted loop>
          <source src="/videos/2.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <h1 className={styles.title}>Authors</h1>
      </section>

      <div className={styles.sortContainer}>
        <span className={styles.sortLabel}>Sort By:</span>
        <div className={styles.radioGroup}>
          <label>
            <input
              type="radio"
              name="sort-authors"
              value="name"
              checked={selectedSort === 'name'}
              onChange={() => handleSortChange('name')}
            />
            <span className={styles.radioLabel}>Name</span>
          </label>
          <label>
            <input
              type="radio"
              name="sort-authors"
              value="quoteCount"
              checked={selectedSort === 'quoteCount'}
              onChange={() => handleSortChange('quoteCount')}
            />
            <span className={styles.radioLabel}>Quote Count</span>
          </label>
        </div>
      </div>

      {isLoading ? (
        <div>Loading...</div>
      ) : errorMessage ? (
        <div>{errorMessage}</div>
      ) : (
        <div className={styles.authorsSection}>
          {authors.map((author) => (
            <div
              key={author.id}
              className={styles.authorCard}
              style={{ backgroundImage: `url(${author.image})` }}
              onClick={() => handleAuthorClick(author.id)}
            >
              <div className={styles.authorInfo}>
                <div className={styles.authorName}>{author.name}</div>
                <div className={styles.quoteCount}>Quotes: {author.quoteCount}</div>
                <div className={styles.authorBio}>{author.bio}</div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default Authors;
